  MODULE('KROJACNICA002.CLW')
AzuriranjeKrojacnica   PROCEDURE
AzuriranjeCUsluga      PROCEDURE
AzuriranjeKrojaca      PROCEDURE
AzuriranjeKlijenata    PROCEDURE
AzuriranjePopravlja    PROCEDURE
AzuriranjSiva          PROCEDURE
IspisSvihKrojaca       PROCEDURE                      !Jednostavno izvjesce
IspisOdabranihKrojaca  PROCEDURE                      !Izvjesce po gumbu
IspisSvihSivanja       PROCEDURE                      !Slozeno izvjesce
  END
